version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    #cria uma copia dos arquivos no volume ao apontar o volume
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=pedro123
      - MYSQL_USER=pedro

    networks:
      - node-network

networks:
   node-network:
     driver: bridge

